INSERT INTO `STATUS` (ID, VERSION, NAME) VALUES
(1, 1, 'Imported lead'),
(2, 1, 'Not contacted'),
(3, 1, 'Contacted'),
(4, 1, 'Customer'),
(5, 1, 'Closed (lost)');

INSERT INTO `COMPANY` (ID, VERSION, NAME) VALUES
(6, 1, 'Phillips Van Heusen Corp.'),
(7, 1, 'Avaya Inc.'),
(8, 1, 'Laboratory Corporation of America Holdings'),
(9, 1, 'AutoZone, Inc.'),
(10, 1, 'Linens ''n Things Inc.');

INSERT INTO `CONTACT` (ID, VERSION, EMAIL, FIRST_NAME, LAST_NAME, COMPANY_ID, STATUS_ID) VALUES
(11, 1, 'ayele.tesfaye@ethiotelecom.et', 'Ayele', 'Tesfaye', 6, 1),
(12, 1, 'mehret.abebe@cbe.et', 'Mehret', 'Abebe', 7, 5),
(13, 1, 'solomon.hailemariam@ethiopianairlines.com', 'Solomon', 'Hailemariam', 8, 3),
(14, 1, 'fikadu.gebre@midrocethiopia.com', 'Fikadu', 'Gebre', 9, 3),
(15, 1, 'tizita.mekonnen@dashenbrewery.com', 'Tizita', 'Mekonnen', 10, 4),
(16, 1, 'biruk.yohannes@ethiotelecom.et', 'Biruk', 'Yohannes', 6, 2),
(17, 1, 'genet.demeke@cbe.et', 'Genet', 'Demeke', 7, 1),
(18, 1, 'yared.gebremedhin@ethiopianairlines.com', 'Yared', 'Gebremedhin', 8, 5),
(19, 1, 'melaku.tadesse@midrocethiopia.com', 'Melaku', 'Tadesse', 9, 1),
(20, 1, 'meskerem.kebede@dashenbrewery.com', 'Meskerem', 'Kebede', 10, 2),
(21, 1, 'samuel.mulugeta@ethiotelecom.et', 'Samuel', 'Mulugeta', 6, 3),
(22, 1, 'sintayehu.kassa@cbe.et', 'Sintayehu', 'Kassa', 7, 1),
(23, 1, 'alemu.tamrat@ethiopianairlines.com', 'Alemu', 'Tamrat', 8, 4),
(24, 1, 'seble.gebre@midrocethiopia.com', 'Seble', 'Gebre', 9, 3),
(25, 1, 'kalkidan.ayele@dashenbrewery.com', 'Kalkidan', 'Ayele', 10, 5),
(26, 1, 'eyasu.fekadu@cbe.et', 'Eyasu', 'Fekadu', 7, 3),
(27, 1, 'miki.girma@ethiotelecom.et', 'Miki', 'Girma', 6, 4),
(28, 1, 'bethelihem.hagos@ethiopianairlines.com', 'Bethelihem', 'Hagos', 8, 1),
(29, 1, 'tewodros.mengistu@midrocethiopia.com', 'Tewodros', 'Mengistu', 9, 5),
(30, 1, 'fikre.mamo@dashenbrewery.com', 'Fikre', 'Mamo', 10, 2),
(31, 1, 'mulu.tessema@midrocethiopia.com', 'Mulu', 'Tessema', 9, 3),
(32, 1, 'abenezer.gudeta@midrocethiopia.com', 'Abenezer', 'Gudeta', 9, 1),
(33, 1, 'getachew.gebrekidan@dashenbrewery.com', 'Getachew', 'Gebrekidan', 10, 2),
(34, 1, 'alemayehu.mulu@midrocethiopia.com', 'Alemayehu', 'Mulu', 9, 1),
(35, 1, 'naol.ayalew@midrocethiopia.com', 'Naol', 'Ayalew', 9, 1);

INSERT INTO `CONTACT` (ID, VERSION, EMAIL, FIRST_NAME, LAST_NAME, COMPANY_ID, STATUS_ID) VALUES
(36, 1, 'yohannes.feleke@cbe.et', 'Yohannes', 'Feleke', 7, 5),
(37, 1, 'birhan.taye@ethiotelecom.et', 'Birhan', 'Taye', 6, 5),
(38, 1, 'saron.gebeyehu@midrocethiopia.com', 'Saron', 'Gebeyehu', 9, 2),
(39, 1, 'seble.girma@ethiopianairlines.com', 'Seble', 'Girma', 8, 4),
(40, 1, 'biniam.wolde@cbe.et', 'Biniam', 'Wolde', 7, 3),
(41, 1, 'wendimu.bekele@dashenbrewery.com', 'Wendimu', 'Bekele', 10, 4),
(42, 1, 'mikiyas.kibret@dashenbrewery.com', 'Mikiyas', 'Kibret', 10, 1),
(43, 1, 'hanna.getahun@ethiotelecom.et', 'Hanna', 'Getahun', 8, 4),
(44, 1, 'fasil.gebru@midrocethiopia.com', 'Fasil', 'Gebru', 9, 3),
(45, 1, 'befekadu.demissie@ethiotelecom.et', 'Befekadu', 'Demissie', 6, 1),
(46, 1, 'haymanot.abay@midrocethiopia.com', 'Haymanot', 'Abay', 9, 5),
(47, 1, 'tesfaye.ayalew@dashenbrewery.com', 'Tesfaye', 'Ayalew', 10, 1),
(48, 1, 'tilahun.hailu@cbe.et', 'Tilahun', 'Hailu', 7, 4),
(49, 1, 'yeshiwas.girma@ethiotelecom.et', 'Yeshiwas', 'Girma', 6, 2),
(50, 1, 'hailu.wondimu@ethiotelecom.et', 'Hailu', 'Wondimu', 8, 1),
(51, 1, 'teshome.abate@ethiotelecom.et', 'Teshome', 'Abate', 6, 1),
(52, 1, 'seifu.tesfaye@ethiotelecom.et', 'Seifu', 'Tesfaye', 6, 5),
(53, 1, 'tamrat.tefera@dashenbrewery.com', 'Tamrat', 'Tefera', 10, 4),
(54, 1, 'kebede.demeke@ethiotelecom.et', 'Kebede', 'Demeke', 8, 2),
(55, 1, 'samrawit.gebregzi@cbe.et', 'Samrawit', 'Gebregzi', 7, 5),
(56, 1, 'tesfahun.bekele@ethiotelecom.et', 'Tesfahun', 'Bekele', 6, 5),
(57, 1, 'teklu.hagos@cbe.et', 'Teklu', 'Hagos', 7, 2),
(58, 1, 'michael.tamiru@midrocethiopia.com', 'Michael', 'Tamiru', 9, 1),
(59, 1, 'befikadu.abera@ethiotelecom.et', 'Befikadu', 'Abera', 8, 5),
(60, 1, 'mesfin.gebremedhin@cbe.et', 'Mesfin', 'Gebremedhin', 7, 5);